linters-settings:
  gocyclo:
    min-complexity: 22
  staticcheck:
    go: "1.18"
    # https://staticcheck.io/docs/options#checks
    checks: ["all","-SA1019"]

linters:
  disable-all: true

  enable:
        - asciicheck
        - forcetypeassert
        - gci
        - gocyclo
        - gofmt
        - goimports
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - ifshort
        - ineffassign
        - misspell
        - nakedret
        - nolintlint
        - prealloc
    ## These are working but disabled for now
          ##  - dogsled # two occurences we cannot really correct
          ##  - dupl # some dups in tests
          ##  - gochecknoinits # we use a lot of init
          ##  - goconst # annoying?
          ##  - godot # annoying?
          ##  - godox # we have a few todo...
          ##  - paralleltest # lots of work to pass
          ##  - nestif # some work to refactor
          ##  - revive # currently a bit buggy with Go 1.18 but works mostly
    ## These are untested yet
      #    - predeclared
      #    - rowserrcheck
      #    - staticcheck
      #    - structcheck
      #    - stylecheck
      #    - tagliatelle
      #    - testpackage
      #    - thelper
      #    - tparallel
      #    - typecheck
      #    - unconvert
      #    - varcheck
      #    - wastedassign
      #    - wrapcheck
      #
## To enable once they work with Go 1.18:
###  - deadcode
###  - depguard
###  - durationcheck
###  - errcheck
###  - errorlint
###  - exhaustive
###  - exportloopref
###  - gocritic
###  - goerr113
###  - gosec
###  - gosimple
###  - govet
###  - importas
###  - makezero
###  - nilerr
###  - unparam
###  - unused

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue
