linters-settings:
  gocyclo:
    min-complexity: 22
  staticcheck:
    go: "1.18"
    # https://staticcheck.io/docs/options#checks
    checks: ["all","-SA1019"]

linters:
  disable-all: true

  enable:
        - asciicheck
        - forcetypeassert
        - gci
        # - gocyclo # need to refactor internal/create/wizard
        - gofmt
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - ifshort
        - ineffassign
        - misspell
        - nakedret
        - nolintlint
        - prealloc
        - predeclared
        - godot
        - nestif
        #- revive # currently a bit buggy with Go 1.18 but works mostly
        ## To enable once they work with Go 1.18:
        ### - deadcode
        ### - depguard
        ### - durationcheck
        ### - errcheck
        ### - errorlint
        ### - exhaustive
        ### - exportloopref
        ### - gocritic
        ### - goerr113
        ### - gosec
        ### - gosimple
        ### - govet
        ### - importas
        ### - makezero
        ### - nilerr
        ### - rowserrcheck
        ### - staticcheck
        ### - structcheck
        ### - stylecheck
        ### - thelper
        ### - tparallel
        ### - typecheck
        ### - unconvert
        ### - unparam
        ### - unused
        ### - varcheck
        ### - wastedassign
        ### - wrapcheck

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue
