run:
  timeout: 5m

linters-settings:
  gocyclo:
    min-complexity: 22
  cyclop:
    max-complexity: 22
    skip-tests: true
  staticcheck:
    go: "1.21"
    # https://staticcheck.io/docs/options#checks
    checks: ["all","-SA1019"]
  funlen:
    lines: -1
    statements: 100

linters:
  enable-all: true
  disable:
  - bodyclose
  - contextcheck
  - deadcode
  - depguard
  - durationcheck
  - dupl
  - dupword
  - exhaustruct
  - exhaustivestruct
  - forbidigo
  - gci
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - goerr113
  - golint
  - gomnd
  - gosec
  - gosimple
  - govet
  - interfacer
  - ifshort
  - inamedparam
  - interfacebloat
  - ireturn
  - lll
  - maintidx
  - maligned
  - musttag
  - nilerr
  - noctx
  - nolintlint
  - nosnakecase
  - paralleltest
  - perfsprint
  - revive
  - rowserrcheck
  - scopelint
  - sqlclosecheck
  - staticcheck
  - structcheck
  - stylecheck
  - tagliatelle
  - testpackage
  - tparallel
  - typecheck
  - unparam
  - unused
  - varcheck
  - varnamelen
  - wastedassign
  - wrapcheck
  - wsl

issues:
  max-issues-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  exclude-dirs:
    - helpers/

output:
  sort-results: true
  sort-order:
    - linter
    - file
