unrestricted_licenses:
  - Apache-2.0
  - MIT
  - BSD-3-Clause
  - BSD-2-Clause
  - 0BSD
reciprocal_licenses:
  - MPL-2.0
  - MPL-2.0-no-copyleft-exception
allowlisted_modules:
# Simplified BSD (BSD-2-Clause): https://github.com/russross/blackfriday/blob/master/LICENSE.txt
- github.com/russross/blackfriday
- github.com/russross/blackfriday/v2
# Apache license
- github.com/dgraph-io/ristretto