// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xc.proto

/*
Package xcpb is a generated protocol buffer package.

It is generated from these files:
	xc.proto

It has these top-level messages:
	Header
	Chunk
	Message
	Identity
	PublicKey
	PrivateKey
	Secring
	Pubring
*/
package xcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublicKeyAlgorithm int32

const (
	PublicKeyAlgorithm_UNKNOWN PublicKeyAlgorithm = 0
	PublicKeyAlgorithm_NACL    PublicKeyAlgorithm = 1
)

var PublicKeyAlgorithm_name = map[int32]string{
	0: "UNKNOWN",
	1: "NACL",
}
var PublicKeyAlgorithm_value = map[string]int32{
	"UNKNOWN": 0,
	"NACL":    1,
}

func (x PublicKeyAlgorithm) String() string {
	return proto.EnumName(PublicKeyAlgorithm_name, int32(x))
}
func (PublicKeyAlgorithm) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Header struct {
	Sender     string            `protobuf:"bytes,1,opt,name=Sender" json:"Sender,omitempty"`
	Recipients map[string][]byte `protobuf:"bytes,2,rep,name=Recipients" json:"Recipients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Header) GetRecipients() map[string][]byte {
	if m != nil {
		return m.Recipients
	}
	return nil
}

type Chunk struct {
	Body []byte `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Chunk) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Message struct {
	Version    uint32   `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	Header     *Header  `protobuf:"bytes,2,opt,name=Header" json:"Header,omitempty"`
	Chunks     []*Chunk `protobuf:"bytes,3,rep,name=Chunks" json:"Chunks,omitempty"`
	Compressed bool     `protobuf:"varint,4,opt,name=Compressed" json:"Compressed,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Message) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetChunks() []*Chunk {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func (m *Message) GetCompressed() bool {
	if m != nil {
		return m.Compressed
	}
	return false
}

type Identity struct {
	Name    string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Comment string `protobuf:"bytes,2,opt,name=Comment" json:"Comment,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
}

func (m *Identity) Reset()                    { *m = Identity{} }
func (m *Identity) String() string            { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()               {}
func (*Identity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Identity) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type PublicKey struct {
	PubKeyAlgo   PublicKeyAlgorithm `protobuf:"varint,1,opt,name=PubKeyAlgo,enum=xcpb.PublicKeyAlgorithm" json:"PubKeyAlgo,omitempty"`
	CreationTime uint64             `protobuf:"varint,2,opt,name=CreationTime" json:"CreationTime,omitempty"`
	PublicKey    []byte             `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Identity     *Identity          `protobuf:"bytes,4,opt,name=Identity" json:"Identity,omitempty"`
	Fingerprint  string             `protobuf:"bytes,5,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
}

func (m *PublicKey) Reset()                    { *m = PublicKey{} }
func (m *PublicKey) String() string            { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()               {}
func (*PublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PublicKey) GetPubKeyAlgo() PublicKeyAlgorithm {
	if m != nil {
		return m.PubKeyAlgo
	}
	return PublicKeyAlgorithm_UNKNOWN
}

func (m *PublicKey) GetCreationTime() uint64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *PublicKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PublicKey) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *PublicKey) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

type PrivateKey struct {
	PublicKey  *PublicKey `protobuf:"bytes,1,opt,name=PublicKey" json:"PublicKey,omitempty"`
	Ciphertext []byte     `protobuf:"bytes,2,opt,name=Ciphertext,proto3" json:"Ciphertext,omitempty"`
	Nonce      []byte     `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Salt       []byte     `protobuf:"bytes,4,opt,name=Salt,proto3" json:"Salt,omitempty"`
}

func (m *PrivateKey) Reset()                    { *m = PrivateKey{} }
func (m *PrivateKey) String() string            { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()               {}
func (*PrivateKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PrivateKey) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PrivateKey) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *PrivateKey) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *PrivateKey) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type Secring struct {
	Version     uint32        `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	PrivateKeys []*PrivateKey `protobuf:"bytes,2,rep,name=PrivateKeys" json:"PrivateKeys,omitempty"`
}

func (m *Secring) Reset()                    { *m = Secring{} }
func (m *Secring) String() string            { return proto.CompactTextString(m) }
func (*Secring) ProtoMessage()               {}
func (*Secring) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Secring) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Secring) GetPrivateKeys() []*PrivateKey {
	if m != nil {
		return m.PrivateKeys
	}
	return nil
}

type Pubring struct {
	Version    uint32       `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	PublicKeys []*PublicKey `protobuf:"bytes,2,rep,name=PublicKeys" json:"PublicKeys,omitempty"`
}

func (m *Pubring) Reset()                    { *m = Pubring{} }
func (m *Pubring) String() string            { return proto.CompactTextString(m) }
func (*Pubring) ProtoMessage()               {}
func (*Pubring) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Pubring) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Pubring) GetPublicKeys() []*PublicKey {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func Init() {
	proto.RegisterType((*Header)(nil), "xcpb.Header")
	proto.RegisterType((*Chunk)(nil), "xcpb.Chunk")
	proto.RegisterType((*Message)(nil), "xcpb.Message")
	proto.RegisterType((*Identity)(nil), "xcpb.Identity")
	proto.RegisterType((*PublicKey)(nil), "xcpb.PublicKey")
	proto.RegisterType((*PrivateKey)(nil), "xcpb.PrivateKey")
	proto.RegisterType((*Secring)(nil), "xcpb.Secring")
	proto.RegisterType((*Pubring)(nil), "xcpb.Pubring")
	proto.RegisterEnum("xcpb.PublicKeyAlgorithm", PublicKeyAlgorithm_name, PublicKeyAlgorithm_value)
}

func Init() { proto.RegisterFile("xc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdd, 0x6e, 0x13, 0x3d,
	0x10, 0xfd, 0x9c, 0xff, 0xcc, 0xee, 0xd7, 0x46, 0x16, 0x42, 0x2b, 0xa8, 0x50, 0xb4, 0x70, 0x11,
	0x15, 0x11, 0xa4, 0x70, 0x53, 0x21, 0xb8, 0x28, 0x51, 0x11, 0x28, 0xb0, 0x44, 0x4e, 0xa1, 0xd7,
	0x9b, 0xcd, 0x28, 0xb1, 0x9a, 0xf5, 0xae, 0xbc, 0x4e, 0x95, 0x7d, 0x00, 0x6e, 0x79, 0x03, 0x1e,
	0x8b, 0xf7, 0x41, 0xb6, 0x77, 0x1b, 0xd3, 0x4a, 0x70, 0x37, 0x73, 0xe6, 0x78, 0xe6, 0x1c, 0x8f,
	0x0d, 0xbd, 0x7d, 0x32, 0xce, 0x65, 0xa6, 0x32, 0xda, 0xda, 0x27, 0xf9, 0x32, 0xfc, 0x49, 0xa0,
	0xf3, 0x01, 0xe3, 0x15, 0x4a, 0xfa, 0x10, 0x3a, 0x0b, 0x14, 0x2b, 0x94, 0x01, 0x19, 0x92, 0x51,
	0x9f, 0x55, 0x19, 0x7d, 0x03, 0xc0, 0x30, 0xe1, 0x39, 0x47, 0xa1, 0x8a, 0xa0, 0x31, 0x6c, 0x8e,
	0xbc, 0xc9, 0xc9, 0x58, 0x9f, 0x1e, 0xdb, 0x93, 0xe3, 0x43, 0xf9, 0x42, 0x28, 0x59, 0x32, 0x87,
	0xff, 0xe8, 0x2d, 0x1c, 0xdf, 0x29, 0xd3, 0x01, 0x34, 0xaf, 0xb1, 0xac, 0xa6, 0xe8, 0x90, 0x3e,
	0x80, 0xf6, 0x4d, 0xbc, 0xdd, 0x61, 0xd0, 0x18, 0x92, 0x91, 0xcf, 0x6c, 0xf2, 0xba, 0x71, 0x46,
	0xc2, 0xc7, 0xd0, 0x9e, 0x6e, 0x76, 0xe2, 0x9a, 0x52, 0x68, 0xbd, 0xcb, 0x56, 0xf6, 0x94, 0xcf,
	0x4c, 0x1c, 0xfe, 0x20, 0xd0, 0xfd, 0x8c, 0x45, 0x11, 0xaf, 0x91, 0x06, 0xd0, 0xfd, 0x86, 0xb2,
	0xe0, 0x99, 0x30, 0x94, 0xff, 0x59, 0x9d, 0xd2, 0x67, 0xb5, 0x43, 0xd3, 0xdd, 0x9b, 0xf8, 0xae,
	0x76, 0x56, 0xbb, 0x7f, 0x0a, 0x1d, 0x33, 0xa8, 0x08, 0x9a, 0xc6, 0xa1, 0x67, 0x59, 0x06, 0x63,
	0x55, 0x89, 0x3e, 0x01, 0x98, 0x66, 0x69, 0x2e, 0xb1, 0x28, 0x70, 0x15, 0xb4, 0x86, 0x64, 0xd4,
	0x63, 0x0e, 0x12, 0x46, 0xd0, 0xfb, 0xb8, 0x42, 0xa1, 0xb8, 0x2a, 0xb5, 0xe0, 0x28, 0x4e, 0xb1,
	0xb2, 0x69, 0x62, 0x2d, 0x72, 0x9a, 0xa5, 0x29, 0x0a, 0x65, 0xb4, 0xf4, 0x59, 0x9d, 0xea, 0x1b,
	0xb8, 0x48, 0x63, 0xbe, 0x0d, 0x9a, 0x06, 0xb7, 0x49, 0xf8, 0x8b, 0x40, 0x7f, 0xbe, 0x5b, 0x6e,
	0x79, 0x32, 0xc3, 0x92, 0x9e, 0x01, 0xcc, 0x77, 0xcb, 0x19, 0x96, 0xe7, 0xdb, 0x75, 0x66, 0xfa,
	0x1e, 0x4d, 0x02, 0x2b, 0xf3, 0x96, 0xa4, 0x4b, 0x92, 0xab, 0x4d, 0xca, 0x1c, 0x2e, 0x0d, 0xc1,
	0x9f, 0x4a, 0x8c, 0x15, 0xcf, 0xc4, 0x25, 0x4f, 0xed, 0x35, 0xb7, 0xd8, 0x1f, 0x18, 0x3d, 0x71,
	0x46, 0x19, 0x15, 0x3e, 0x73, 0x66, 0x9f, 0x1e, 0x9c, 0x19, 0xdf, 0xde, 0xe4, 0xc8, 0x4e, 0xae,
	0x51, 0x76, 0x70, 0x3e, 0x04, 0xef, 0x3d, 0x17, 0x6b, 0x94, 0xb9, 0xe4, 0x42, 0x05, 0x6d, 0xe3,
	0xc8, 0x85, 0xc2, 0xef, 0x04, 0x60, 0x2e, 0xf9, 0x4d, 0xac, 0x50, 0x37, 0x7f, 0xe1, 0x8e, 0x26,
	0xa6, 0xfb, 0xf1, 0x1d, 0x5f, 0xae, 0x16, 0xbd, 0x05, 0x9e, 0x6f, 0x50, 0x2a, 0xdc, 0xab, 0xea,
	0xc9, 0x38, 0x88, 0xbe, 0xcb, 0x28, 0x13, 0x09, 0x56, 0x2e, 0x6c, 0xa2, 0xf7, 0xb1, 0x88, 0xb7,
	0xca, 0xa8, 0xf7, 0x99, 0x89, 0xc3, 0x2b, 0xe8, 0x2e, 0x30, 0x91, 0x5c, 0xac, 0xff, 0xf2, 0x7e,
	0x26, 0xe0, 0x1d, 0xb4, 0xd6, 0x1f, 0x60, 0x50, 0xe9, 0xbb, 0x2d, 0x30, 0x97, 0x14, 0x5e, 0x42,
	0x77, 0xbe, 0x5b, 0xfe, 0xa3, 0xf1, 0x4b, 0xb3, 0x4f, 0x6b, 0xaa, 0xee, 0x7b, 0xcf, 0xb7, 0x43,
	0x39, 0x7d, 0x0e, 0xf4, 0xfe, 0xa2, 0xa9, 0x07, 0xdd, 0xaf, 0xd1, 0x2c, 0xfa, 0x72, 0x15, 0x0d,
	0xfe, 0xa3, 0x3d, 0x68, 0x45, 0xe7, 0xd3, 0x4f, 0x03, 0xb2, 0xec, 0x98, 0x6f, 0xfe, 0xea, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x28, 0x59, 0x41, 0xf2, 0x03, 0x00, 0x00,
}
